### ISSUE TITLE
Is this code works for pcl-1.7.2 ubuntu 14.04

### ISSUE THREAD

**Issue by ljc19800331** [ryanfb/pcl-tools#6]
Hello,

I got error when I git clone this code and build the code by typing

cd pcl-tools
mkdir build
cd build
cmake ..
make

But got the following error: 

/home/maguangshen/pcl-tools/src/pcd_viewer.cpp: In function ‘int main(int, char**)’:
/home/maguangshen/pcl-tools/src/pcd_viewer.cpp:612:56: error: expected primary-expression before ‘,’ token
       p->addPointCloudPrincipalCurvatures<pcl::PointXYZ, pcl::Normal> (cloud_xyz, cloud_normals, cloud_pc, factor, pc_scale, cloud_name_normals_pc.str (), viewport);
                                                        ^
/home/maguangshen/pcl-tools/src/pcd_viewer.cpp:612:69: error: expected primary-expression before ‘>’ token
       p->addPointCloudPrincipalCurvatures<pcl::PointXYZ, pcl::Normal> (cloud_xyz, cloud_normals, cloud_pc, factor, pc_scale, cloud_name_normals_pc.str (), viewport);
                                                                     ^
/home/maguangshen/pcl-tools/src/pcd_viewer.cpp:631:36: error: expected type-specifier
           color_handler.reset (new pcl::visualization::PointCloudColorHandlerLabelField<pcl::PCLPointCloud2> (cloud, !use_optimal_l_colors));
                                    ^
make[2]: *** [CMakeFiles/pcd_viewer.dir/src/pcd_viewer.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcd_viewer.dir/all] Error 2
make: *** [all] Error 2

**Comment by sebinefrancis** [comment]
I have built it successfully in Ubuntu 20.04 with boost version "1.71.0", with minor modifications in two files:

1. I got error regarding `boost::thread::sleep`. It turned out to be issue with the old and new boost library versions. I found solution from : https://stackoverflow.com/a/4265343/6394769  So I made changes in **pcd_viewer.cpp**. Changed 
'`boost::this_thread::sleep`' to '`boost::this_thread::sleep_for`' and added 
```
#include <boost/chrono.hpp>
#include <boost/thread/thread.hpp>
``` 
because my version of boost was newer.

2. Then I got some error 'undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3''. To solve this I had to edit **CMakeLists.txt** and add `thread` to this line after system like this: `find_package(Boost COMPONENTS REQUIRED system  thread )`

After these changes it built successfully. Hope this helps someone.

**Comment by ryanfb** [comment]
Thanks for the feedback - this should now work on latest Ubuntu with libpcl-dev 1.12.1.
